config/routes.rb
Rails.application.routes.draw do
  # root 'devise/sessions#new'
  root 'dojos#index'
  devise_for :managers
  resources :dojos do
    resources :students
  end
end


# Prefix                            Verb   URI Pattern                                                                              Controller#Action
# =====================================================================================================================================================
# root                              GET    /                                                                                        devise/sessions#new
# --------------------------------------------------------------------------------------------------------------------------------- [ Students Routes ]
# dojo_students                     GET    /dojos/:dojo_id/students(.:format)                                                       students#index
#                                   POST   /dojos/:dojo_id/students(.:format)                                                       students#create
# new_dojo_student                  GET    /dojos/:dojo_id/students/new(.:format)                                                   students#new
# edit_dojo_student                 GET    /dojos/:dojo_id/students/:id/edit(.:format)                                              students#edit
# dojo_student                      GET    /dojos/:dojo_id/students/:id(.:format)                                                   students#show
#                                   PATCH  /dojos/:dojo_id/students/:id(.:format)                                                   students#update
#                                   PUT    /dojos/:dojo_id/students/:id(.:format)                                                   students#update
#                                   DELETE /dojos/:dojo_id/students/:id(.:format)                                                   students#destroy
# --------------------------------------------------------------------------------------------------------------------------------- [ Devise Routes ]
# new_manager_session               GET    /managers/sign_in(.:format)                                                              devise/sessions#new
# manager_session                   POST   /managers/sign_in(.:format)                                                              devise/sessions#create
# destroy_manager_session           DELETE /managers/sign_out(.:format)                                                             devise/sessions#destroy
# new_manager_password              GET    /managers/password/new(.:format)                                                         devise/passwords#new
# edit_manager_password             GET    /managers/password/edit(.:format)                                                        devise/passwords#edit
# manager_password                  PATCH  /managers/password(.:format)                                                             devise/passwords#update
#                                   PUT    /managers/password(.:format)                                                             devise/passwords#update
#                                   POST   /managers/password(.:format)                                                             devise/passwords#create
# cancel_manager_registration       GET    /managers/cancel(.:format)                                                               devise/registrations#cancel
# new_manager_registration          GET    /managers/sign_up(.:format)                                                              devise/registrations#new
# edit_manager_registration         GET    /managers/edit(.:format)                                                                 devise/registrations#edit
# manager_registration              PATCH  /managers(.:format)                                                                      devise/registrations#update
#                                   PUT    /managers(.:format)                                                                      devise/registrations#update
#                                   DELETE /managers(.:format)                                                                      devise/registrations#destroy
#                                   POST   /managers(.:format)                                                                      devise/registrations#create
# new_manager_confirmation          GET    /managers/confirmation/new(.:format)                                                     devise/confirmations#new
# manager_confirmation              GET    /managers/confirmation(.:format)                                                         devise/confirmations#show
#                                   POST   /managers/confirmation(.:format)                                                         devise/confirmations#create
# --------------------------------------------------------------------------------------------------------------------------------- [ Dojos Routes ]
#     dojos                         GET    /dojos(.:format)                                                                         dojos#index
#                                   POST   /dojos(.:format)                                                                         dojos#create
#  new_dojo                         GET    /dojos/new(.:format)                                                                     dojos#new
# edit_dojo                         GET    /dojos/:id/edit(.:format)                                                                dojos#edit
#      dojo                         GET    /dojos/:id(.:format)                                                                     dojos#show
#                                   PATCH  /dojos/:id(.:format)                                                                     dojos#update
#                                   PUT    /dojos/:id(.:format)                                                                     dojos#update
#                                   DELETE /dojos/:id(.:format)                                                                     dojos#destroy
# --------------------------------------------------------------------------------------------------------------------------------- [ Helper Routes ]
# rails_service_blob                GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation         GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
# rails_disk_service                GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service         PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
# rails_direct_uploads              POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :dojo
  validates  :first_name, :last_name, :email, presence: true, length: { in: 2..25 }
  validates  :email, uniqueness: { case_sensitive: false }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:first_name, :last_name, :email, :dojo_id]

  # =============================
  # GET Request - Renders [.html]
  # =============================
  def new
    # unless params[:manager_id].present?
    #   redirect_to new_manager_session_path
    # else
      @dojos = Dojo.all
      @student = Student.new
      @dojoId = params[:dojo_id]
      @this_dojo = Dojo.find(@dojoId)
      # ---------------------------------- [ Put in Session ]
      session[:student_id] = params[:id]
      session[:dojo_id] = params[:dojo_id]
      # ----------------------------------
    # end
  end

  # =============================
  # GET Request - Renders [.html]
  # =============================
  def show
    # unless params[:manager_id].present?
    #   redirect_to new_manager_session_path
    # else
      @student = Student.find(params[:id])
      @this_dojo = Dojo.find(params[:dojo_id])
      @this_student = "#{@student.first_name} #{@student.last_name}"

      # ------------------------------ [ Put in Session ]
      session[:dojoid] = @this_dojo.id
      # ------------------------------
    # end
  end


  # =============================
  # GET Request - Renders [.html]
  # =============================
  def edit
    # unless params[:manager_id].present?
    #   redirect_to new_manager_session_path
    # else
      @dojos = Dojo.all
      @student = Student.find(params[:id])
      @this_dojo = Dojo.find(params[:dojo_id])

      # ---------------------------------- [ Put in Session ]
      session[:student_id] = params[:id]
      session[:branch] = @this_dojo.branch
      # ----------------------------------
      render "edit"
    # end
  end

  # ====================
  # POST Request [.html]
  # POST Request [.json]
  # ====================
  def create
    @student = Student.new(validate_params)
    respond_to do |format|
      if @student.save
        # format.html { redirect_to dojo_student_url, notice: 'Student was successfully created.' }
        format.html { redirect_to dojo_path(@this_dojo), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # =========================
  # PATCH/PUT Request [.html]
  # PATCH/PUT Request [.json]
  # =========================
  def update
    respond_to do |format|
      if @student.update(validate_params)
        # format.html { redirect_to dojo_student_url, notice: 'Student was successfully updated.' }
        format.html { redirect_to dojo_student_path(@student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end


  # ======================
  # DELETE /student/1
  # DELETE /student/1.json
  # ======================
  def destroy
    Student.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to `/dojo/#{params[:dojo_id]}`, notice: 'Student was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Sanatizing/Validating Parameters...
    def validate_params
      params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_errors.html.erb
<% if student.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:
  </h2>
  <ul>
    <% student.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/students/edit.html.erb
<!-- EDIT Dojo Student PAGE COMPONENT -->

<div class="container">
    <!--
    =========================
    [ Error Display... if any
    =========================
    -->
    <% if @student.errors.any? %>
    <div id="error_explanation">
        <h5>
            <span class="blue-text"><%= pluralize(@student.errors.count, "error") %></span>
            prohibited this student from being submitted:
        </h5>
        <ul>
            <% @student.errors.full_messages.each do |message| %>
            <li class="red-text">
                <span class="blue-text right-margin1">&#187;</span>
                <%= message %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <h2 class="_header">Edittin <span class="white-text"><%= @student.first_name %>'s Profile</span></h2>

    <%= form_with(model: @student, url: dojo_student_path, local: true, class: 'mt-4') do |f| %>
        <div class="row">
            <div class="input-field col s6">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", :class => 'white-text' %>
            </div>
            <div class="input-field col s6">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", :class => 'white-text' %>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6">
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => 'white-text' %>
            </div>
            <div class="input-field col s6">
                <%= f.select :dojo_id, options_for_select(all_dojos.collect{|dojo| [dojo.branch, dojo.id] }), :class => 'custom-select' %>
                <%= f.label :branch %>
            </div>
        </div>

        <button
            class="btn waves-effect sn logreg"
            type="submit"
            name="action"
            style="width:10rem; margin:1rem">SUBMIT
            <i class="material-icons right blue-text">send</i>
        </button>
    <% end %>
</div>

<%= link_to 'Back', url_for(:back), class:'btn sn bottom-links' %>
<%= link_to 'Show', @this_dojo, class:'btn sn bottom-links', style:'margin-left:0.2rem' %>

app/views/students/new.html.erb
<!-- ADD New Student to a Student PAGE COMPONENT -->

<div class="container">

    <%= render "errors", student: @student %>

    <h2>Add New <span class="white-text">Student</span></h2>

    <%= form_with(model: @student, url: dojo_students_path, local: true, class: 'mt-4') do |f| %>
        <div class="row">
            <div class="input-field col s6">
                <%= f.label :first_name %>
                <%= f.text_field :first_name,  autocomplete: "first_name", :class => 'white-text' %>
            </div>
            <div class="input-field col s6">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, autocomplete: "last_name", :class => 'white-text' %>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => 'white-text' %>
            </div>
            <div class="input-field col s6">
                <%= f.label :branch %>
                <%= select_tag :dojo_id, options_for_select(all_dojos.collect{|dojo| [dojo.id, dojo.branch] }), :class => 'custom-select' %>
            </div>
        </div>

        <button
            class="btn waves-effect sn logreg"
            type="submit"
            name="action"
            style="width:10rem; margin: 1rem">SUBMIT
            <i class="material-icons right blue-text">send</i>
        </button>
    <% end %>
</div>

<%= link_to 'Show', @this_dojo, class:'btn sn bottom-links' %>
<%= link_to 'Back', url_for(:back), class:'btn sn bottom-links right limits' %>

app/views/students/show.html.erb
<div class="container" style="padding: 2rem 4rem !important">
    <!--
    ==========
    Header...
    ==========
    -->
    <h2 class="student_header"><%= @this_student %>'s <span>Profile</span></h2>
    <ul class="col s12">
        <li class="col s6 mt-3 mb-3"><h6>Branch: <span class="blue-text"><%= @this_dojo.branch %></span></li></h6>
        <li class="col s6 mt-3 mb-3"><h6>Level: <span class="blue-text">Unkown</span></li></h6>
        <li class="col s6 mt-3 mb-3"><h6>Email: <span class="blue-text"><%= @student.email %></span></li></h6>
    </ul>

    <!--
    =========================
    Dojo/Student Cohort Table
    =========================
    -->
    <table class="highlight">
        <h4>Cohort</h4>
        <thead>
        <tr>
            <th class="theader">First Name</th>
            <th class="theader">Last Name </th>
            <th class="theader">Email     </th>
        </tr>
        </thead>
        <tbody>
            <div>
                <% @this_dojo.students.each do |student| %>
                <tr class="trbody">
                    <td><%= student.first_name %></td>
                    <td><%= student.last_name  %></td>
                    <td><%= student.email      %></td>
                </tr>
                <% end %>
            </div>
        </tbody>
    </table>

    <!--
    Actions
    -->
    <div class="grided">
        <%= link_to  "Edit", edit_dojo_student_path(@this_dojo), class:'btn edit sn blue-text top-margin6', style:'border-radius:.25rem !important' %>
        <%= link_to 'Delete', dojo_student_path(@student), class:'btn delete sn red-text top-margin6', style:'border-radius:.25rem !important', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
</div>

<%= link_to 'Back', url_for(:back), class:'btn sn bottom-links right limits' %>