config/routes.rb
Rails.application.routes.draw do
  # root 'devise/sessions#new'
  root 'dojos#index'
  devise_for :managers
  resources :dojos do
    resources :students
  end
end


# Prefix                            Verb   URI Pattern                                                                              Controller#Action
# =====================================================================================================================================================
# root                              GET    /                                                                                        devise/sessions#new
# --------------------------------------------------------------------------------------------------------------------------------- [ Students Routes ]
# dojo_students                     GET    /dojos/:dojo_id/students(.:format)                                                       students#index
#                                   POST   /dojos/:dojo_id/students(.:format)                                                       students#create
# new_dojo_student                  GET    /dojos/:dojo_id/students/new(.:format)                                                   students#new
# edit_dojo_student                 GET    /dojos/:dojo_id/students/:id/edit(.:format)                                              students#edit
# dojo_student                      GET    /dojos/:dojo_id/students/:id(.:format)                                                   students#show
#                                   PATCH  /dojos/:dojo_id/students/:id(.:format)                                                   students#update
#                                   PUT    /dojos/:dojo_id/students/:id(.:format)                                                   students#update
#                                   DELETE /dojos/:dojo_id/students/:id(.:format)                                                   students#destroy
# --------------------------------------------------------------------------------------------------------------------------------- [ Devise Routes ]
# new_manager_session               GET    /managers/sign_in(.:format)                                                              devise/sessions#new
# manager_session                   POST   /managers/sign_in(.:format)                                                              devise/sessions#create
# destroy_manager_session           DELETE /managers/sign_out(.:format)                                                             devise/sessions#destroy
# new_manager_password              GET    /managers/password/new(.:format)                                                         devise/passwords#new
# edit_manager_password             GET    /managers/password/edit(.:format)                                                        devise/passwords#edit
# manager_password                  PATCH  /managers/password(.:format)                                                             devise/passwords#update
#                                   PUT    /managers/password(.:format)                                                             devise/passwords#update
#                                   POST   /managers/password(.:format)                                                             devise/passwords#create
# cancel_manager_registration       GET    /managers/cancel(.:format)                                                               devise/registrations#cancel
# new_manager_registration          GET    /managers/sign_up(.:format)                                                              devise/registrations#new
# edit_manager_registration         GET    /managers/edit(.:format)                                                                 devise/registrations#edit
# manager_registration              PATCH  /managers(.:format)                                                                      devise/registrations#update
#                                   PUT    /managers(.:format)                                                                      devise/registrations#update
#                                   DELETE /managers(.:format)                                                                      devise/registrations#destroy
#                                   POST   /managers(.:format)                                                                      devise/registrations#create
# new_manager_confirmation          GET    /managers/confirmation/new(.:format)                                                     devise/confirmations#new
# manager_confirmation              GET    /managers/confirmation(.:format)                                                         devise/confirmations#show
#                                   POST   /managers/confirmation(.:format)                                                         devise/confirmations#create
# --------------------------------------------------------------------------------------------------------------------------------- [ Dojos Routes ]
#     dojos                         GET    /dojos(.:format)                                                                         dojos#index
#                                   POST   /dojos(.:format)                                                                         dojos#create
#  new_dojo                         GET    /dojos/new(.:format)                                                                     dojos#new
# edit_dojo                         GET    /dojos/:id/edit(.:format)                                                                dojos#edit
#      dojo                         GET    /dojos/:id(.:format)                                                                     dojos#show
#                                   PATCH  /dojos/:id(.:format)                                                                     dojos#update
#                                   PUT    /dojos/:id(.:format)                                                                     dojos#update
#                                   DELETE /dojos/:id(.:format)                                                                     dojos#destroy
# --------------------------------------------------------------------------------------------------------------------------------- [ Helper Routes ]
# rails_service_blob                GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation         GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
# rails_disk_service                GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service         PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
# rails_direct_uploads              POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/models/dojo.rb
class Dojo < ApplicationRecord
    has_many  :managers, :dependent => :destroy
    has_many  :students, :dependent => :destroy
    validates :street, :city, presence: true, length: { minimum: 2 }
    validates :branch, uniqueness: { case_sensitive: false }
end

app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  before_action :set_dojo, only: [:show, :edit, :update, :destroy]

  # ===============
  # GET /dojos
  # GET /dojos.json
  # ===============
  def index
      @dojos = Dojo.all
  end

  # =================
  # GET /dojos/1
  # GET /dojos/1.json
  # =================
  def show
    # unless params[:manager_id].present?
      # redirect_to new_manager_session_path
    # else
      @students = Student.all
      # --------------- [ Put in session ]
      session[:dojo_id] = params[:dojo_id]
      # ----------------------------------
    # end
  end

  # ==============
  # GET /dojos/new
  # ==============
  def new
    # unless params[:manager_id].present?
      # redirect_to new_manager_session_path
    # else
    @dojo = Dojo.new
    # end
  end

  # =================
  # GET /dojos/1/edit
  # =================
  def edit
    # unless params[:manager_id].present?
      # redirect_to new_manager_session_path
    # end
  end

  # ================
  # POST /dojos
  # POST /dojos.json
  # ================
  def create
    # @dojo = current_manager.dojos.build(dojo_params)
    @dojo = Dojo.new(dojo_params)
    respond_to do |format|
      if @dojo.save
        format.html { redirect_to @dojo, notice: 'Dojo was successfully created.' }
        format.json { render :show, status: :created, location: @dojo }
      else
        format.html { render :new }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # =======================
  # PATCH/PUT /dojos/1
  # PATCH/PUT /dojos/1.json
  # =======================
  def update
    respond_to do |format|
      if @dojo.update(dojo_params)
        format.html { redirect_to @dojo, notice: 'Dojo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dojo }
      else
        format.html { render :edit }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # ====================
  # DELETE /dojos/1
  # DELETE /dojos/1.json
  # ====================
  def destroy
    @dojo.destroy
    respond_to do |format|
      format.html { redirect_to dojos_url, notice: 'Dojo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dojo
      @dojo = Dojo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dojo_params
      params.require(:dojo).permit(:branch, :street, :city, :state, :manager_id)
    end
end

app/helpers/dojos_helper.rb
module DojosHelper
end

app/views/dojos/_errors.html.erb
<% if dojo.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(dojo.errors.count, "error") %> prohibited this dojo from being saved:
  </h2>
  <ul>
    <% dojo.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/dojos/_form.html.erb
<%= form_with(model: dojo, local: true) do |form| %>
  <div class="row">
    <div class="input-field col s6">
      <%= select_tag :dojo_id, options_for_select(all_dojos.collect{|dojo| [dojo.id, dojo.branch] }), class:'custom-select' %>
      <%= form.label :branch %>
    </div>
    <div class="input-field col s6">
      <%= form.select :id_manager, options_for_select(all_managers.collect{|manager| [manager.first_name, manager.id]}), class:'custom-select' %>
      <%= form.label :manager %>
    </div>
  </div>

  <div class="row top-margin4">
    <div class="input-field col s6">
      <%= form.label :location %>
    </div>
    <div class="input-field col s10 col-sm-10 left-margin6">
      <%= form.text_field :street, class:'white-text' %>
      <%= form.label :street %>
    </div>
    <div class="input-field col s10 col-sm-10 left-margin6">
      <%= form.text_field :city, class:'white-text' %>
      <%= form.label :city %>
    </div>
    <div class="input-field col s10 col-sm-10 left-margin6 bottom-margin6">
      <%= form.select :state, options_for_select(us_states),{}, class: 'custom-select' %>
      <%= form.label :state %>
    </div>
  </div>

  <button class="btn waves-effect sn logreg" type="submit" name="action" style="width:10rem; margin: 0 1rem">SUBMIT
    <i class="material-icons right blue-text">send</i>
  </button>
<% end %>

app/views/dojos/edit.html.erb
<div class="container">
    <%= render 'errors', dojo: @dojo %>
    <h2>Editing <span class="white-text">Dojo</span></h2>
    <%= render 'form', dojo: @dojo %>
</div>

<%= link_to 'Show', @dojo, class:'btn btn-small sn bottom-links' %>
<%= link_to 'Back', url_for(:back), class:'btn sn bottom-links right limits' %>

app/views/dojos/index.html.erb
<div class="container">
    <h2>
        Listing
        <span class="white-text"><%= @dojos.count %></span>
        Dojos
    </h2>

    <table class="highlight">
        <thead>
            <tr>
                <th class="theader">Coding Dojo Branch</th>
                <th class="theader">Street            </th>
                <th class="theader">City              </th>
                <th class="theader">State             </th>
                <th class="theader">Actions           </th>
            </tr>
        </thead>
        <tbody>
            <div>
                <% @dojos.each do |dojo| %>
                <tr class="trbody">
                    <td><%= dojo.branch %></td>
                    <td><%= dojo.street %></td>
                    <td><%= dojo.city   %></td>
                    <td><%= dojo.state  %></td>
                    <td>
                        <%= link_to 'Show', dojo, class:'sn show' %>
                        <%= link_to 'Edit', edit_dojo_path(dojo), class:'sn edit' %>
                        <%= link_to 'Delete', dojo, class:'sn delete', method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                </tr>
                <% end %>
            </div>
        </tbody>
    </table>
</div>

<div class="row center-align">
    <div class="new_dojo">
        <a href="/dojos/new" class="btn waves-effect sn bottom-margin2 logreg" style="width:12rem;">NEW DOJO
            <i class="material-icons right blue-text">send</i>
        </a>
    </div>
</div>

app/views/dojos/new.html.erb
<div class="container">
    <%= render 'errors', dojo: @dojo %>
    <h2>New <span class="white-text">Dojo</span></h2>
    <%= render 'form', dojo: @dojo %>
</div>

<%= link_to 'Back', url_for(:back), class:'btn sn bottom-links' %>

app/views/dojos/show.html.erb
<div class="container">
    <h2 class="heading-view">Coding Dojo<span class="white-text"> <%= @dojo.city %></span></h2>
    <ul class="col s12">
        <li class="col s6"><h6>Address: <span class="grey-text"><%= @dojo.street %></span></li></h6>
        <li class="col s6">
            <h6>City: <span class="grey-text"><%= @dojo.city   %></span></h6>
            <h6>State: <span class="grey-text"><%= @dojo.state  %></span></h6>
        </li>
    </ul>

    <table class="highlight">
        <thead>
        <tr>
            <th class="theader">First Name</th>
            <th class="theader">Last Name </th>
            <th class="theader">Email     </th>
            <th class="theader">Actions   </th>
        </tr>
        </thead>
        <tbody>
            <% if @students %>
            <div>
                <% @students.each do |student| %>
                <tr class="trbody">
                    <td><%= student.first_name %></td>
                    <td><%= student.last_name  %></td>
                    <td><%= student.email      %></td>
                    <td>
                        <%= link_to 'Show', dojo_student_path(student), class:'sn show' %>
                        <%= link_to 'Edit', edit_dojo_student_path(student), class:'sn edit' %>
                        <%= link_to 'Delete', dojo_student_path(student), class:'sn delete', method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                </tr>
                <% end %>
            </div>
            <% else %>
            <h1>No Student Has Been  Added, Yet!</h1>
            <% end %>
        </tbody>
    </table>
</div>

<%= link_to 'Add New Student', new_dojo_student_path(@dojo), class:'btn sn bottom-links' %>
<%= link_to 'Edit Dojo', edit_dojo_path(@dojo), class:'btn sn bottom-links', style:'margin-left:0.2rem !important'%>
<%= link_to 'Back', url_for(:back), class:'btn sn bottom-links right limits' %>