config/routes.rb
Rails.application.routes.draw do
  # root 'devise/sessions#new'
  root 'dojos#index'
  devise_for :managers
  resources :dojos do
    resources :students
  end
end


# Prefix                            Verb   URI Pattern                                                                              Controller#Action
# =====================================================================================================================================================
# root                              GET    /                                                                                        devise/sessions#new
# --------------------------------------------------------------------------------------------------------------------------------- [ Students Routes ]
# dojo_students                     GET    /dojos/:dojo_id/students(.:format)                                                       students#index
#                                   POST   /dojos/:dojo_id/students(.:format)                                                       students#create
# new_dojo_student                  GET    /dojos/:dojo_id/students/new(.:format)                                                   students#new
# edit_dojo_student                 GET    /dojos/:dojo_id/students/:id/edit(.:format)                                              students#edit
# dojo_student                      GET    /dojos/:dojo_id/students/:id(.:format)                                                   students#show
#                                   PATCH  /dojos/:dojo_id/students/:id(.:format)                                                   students#update
#                                   PUT    /dojos/:dojo_id/students/:id(.:format)                                                   students#update
#                                   DELETE /dojos/:dojo_id/students/:id(.:format)                                                   students#destroy
# --------------------------------------------------------------------------------------------------------------------------------- [ Devise Routes ]
# new_manager_session               GET    /managers/sign_in(.:format)                                                              devise/sessions#new
# manager_session                   POST   /managers/sign_in(.:format)                                                              devise/sessions#create
# destroy_manager_session           DELETE /managers/sign_out(.:format)                                                             devise/sessions#destroy
# new_manager_password              GET    /managers/password/new(.:format)                                                         devise/passwords#new
# edit_manager_password             GET    /managers/password/edit(.:format)                                                        devise/passwords#edit
# manager_password                  PATCH  /managers/password(.:format)                                                             devise/passwords#update
#                                   PUT    /managers/password(.:format)                                                             devise/passwords#update
#                                   POST   /managers/password(.:format)                                                             devise/passwords#create
# cancel_manager_registration       GET    /managers/cancel(.:format)                                                               devise/registrations#cancel
# new_manager_registration          GET    /managers/sign_up(.:format)                                                              devise/registrations#new
# edit_manager_registration         GET    /managers/edit(.:format)                                                                 devise/registrations#edit
# manager_registration              PATCH  /managers(.:format)                                                                      devise/registrations#update
#                                   PUT    /managers(.:format)                                                                      devise/registrations#update
#                                   DELETE /managers(.:format)                                                                      devise/registrations#destroy
#                                   POST   /managers(.:format)                                                                      devise/registrations#create
# new_manager_confirmation          GET    /managers/confirmation/new(.:format)                                                     devise/confirmations#new
# manager_confirmation              GET    /managers/confirmation(.:format)                                                         devise/confirmations#show
#                                   POST   /managers/confirmation(.:format)                                                         devise/confirmations#create
# --------------------------------------------------------------------------------------------------------------------------------- [ Dojos Routes ]
#     dojos                         GET    /dojos(.:format)                                                                         dojos#index
#                                   POST   /dojos(.:format)                                                                         dojos#create
#  new_dojo                         GET    /dojos/new(.:format)                                                                     dojos#new
# edit_dojo                         GET    /dojos/:id/edit(.:format)                                                                dojos#edit
#      dojo                         GET    /dojos/:id(.:format)                                                                     dojos#show
#                                   PATCH  /dojos/:id(.:format)                                                                     dojos#update
#                                   PUT    /dojos/:id(.:format)                                                                     dojos#update
#                                   DELETE /dojos/:id(.:format)                                                                     dojos#destroy
# --------------------------------------------------------------------------------------------------------------------------------- [ Helper Routes ]
# rails_service_blob                GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation         GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
# rails_disk_service                GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service         PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
# rails_direct_uploads              POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/views/layouts/_errors.html.erb
<% if flash %>
  <% flash.each do |message_type, message| %>
    <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    © <%= Time.current.year %> ObiFenix
    <div class="grey-text text-lighten-4 right footer-color">
      <a href="https://github.com/ObiFenix/"><i class="fa fa-github"></i> Github</a>
      <a href="https://www.linkedin.com/in/obifenix/"><i class="fa fa-linkedin"></i> LinkedIn</a>
      <a href="https://portfolio-p3ks1z9oh.now.sh/"><i class="fa fa-google-plus-official" style="vertical-align: middle;"></i> MyWebsite+</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="dark">
  <div class="nav-wrapper">
    <a href="/"><img src="/assets/codingdojo.png"</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="/">Home</a></li>
      <li><a href="/managers/edit">camaleon<span class="blue-text">Profile</span></a></li>
      <% unless !current_manager %>
      <li><a href="/managers/edit"><%= current_manager.first_name %><span class="blue-text">Profile</span></a></li>
      <li><%= link_to "Log out", "/logout", data: { method: :delete, confirm: "Are you sure?"} %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_main.html.erb
<main class="container-fluid">
  <%- if controller_name == 'sessions' %>
  <div class="container-logreg" role="alert" style="border-bottom:none !important;">
  <% else %>
  <div class="container" role="alert" style="border-bottom:none !important;">
  <% end %>
      <% if notice %>
      <p class="msg msg-success z-depth scale-transition"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="msg msg-error z-depth-3 scale-transition"><%= alert %></p>
      <% end %>
  </div>

  <%= yield %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingdojoStudentMngt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'main.js', 'data-turbolinks-track': 'reload' %>
    <style>
      .scrollbar{
        height: 200px;
        overflow-y: scroll;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/main' %>
    <%= render 'layouts/footer' %>

    <!-- Required JS Files -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
  </body>
</html>